###
GET http://localhost:8000/api/v1/setting-types


###
POST http://localhost:8000/api/v1/setting-types
Content-Type: application/json

{
  "title": "Units of Measure",
  "description": "Unit of measure for CWP Projects"
}


###
PUT http://localhost:8000/api/v1/setting-types/1
Content-Type: application/json

{
  "title": "application",
  "description": "General application related settings"
}



###
GET http://localhost:8000/api/v1/settings


###
POST http://localhost:8000/api/v1/settings
Content-Type: application/json

{
  "settingTypeId": 1,
  "title": "units-of-measure",
  "description": "Units of Measure for CWP Projects",
  "value": {"metric": "Energy", "unit": "kWh"}
}


###
GET http://localhost:8000/api/v1/settings/1



