###
GET http://localhost:8000/api/v1/projects



###
POST http://localhost:8000/api/v1/projects
Content-Type: application/json

{
    "title": "Angola",
    "description": "600 MW Green Ammonia Project",
    "project_manager": "Louis Becker",
    "logo_url": "/images/flag_of_angola.png"
}

###
GET http://localhost:8000/api/v1/projects/1


###
GET http://localhost:8000/api/v1/projects/1/components


###
PUT http://localhost:8000/api/v1/projects/1
Content-Type: application/json

{
    "logo_url": "http://localhost:8000/api/v1/static/project_logos/Flag_of_Mauritania.svg"
}

###
DELETE http://localhost:8000/api/v1/projects/3


###
GET http://localhost:8000/api/v1/projects/framework